<?php

/**
 * @file
 * Contains bits_countries.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bits_countries_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bits_countries module.
    case 'help.page.bits_countries':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Manage countries and cities information') . '</p>';
      return $output;

    default:
  }
}
