<?php

/**
 * @file
 * Contains bits_redirect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bits_redirect_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bits_redirect module.
    case 'help.page.bits_redirect':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Show rest resource with redirects urls') . '</p>';
      return $output;

    default:
  }
}
