<?php

/**
 * @file
 * This file provides all hooks to offers a service with REST.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function adf_content_types_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.adf_content_types':
      return check_markup(file_get_contents(dirname(__FILE__) . "/README.txt"));
  }
}
