<?php

/**
 * @file
 * Contains bits_prodandserv.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bits_routes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bits_prodandserv module.
    case 'help.page.bits_prodandserv':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Modulo que contiene la entidad de configuracion bits_routes') . '</p>';
      return $output;

    default:
  }
}

function bits_routes_theme() {
  $theme['page__home'] = [
    'template' => 'page__home',
    'variables' => ['homeorerrorpage' => NULL],

  ];
  $theme['page__404'] = [
    'template' => 'page__404',
    'variables' => ['homeorerrorpage' => NULL],
  ];
  $theme['page__403'] = [
    'template' => 'page__403',
    'variables' => ['homeorerrorpage' => NULL],
  ];
  return $theme;
}
