parameters:
  cors.config:
    enabled: true
    # Specify allowed headers, like 'x-allowed-header'.
    allowedHeaders: ['Access-Control-Allow-Origin', 'x-csrf-token','Content-Type','x-auth','limit','offset','order']
    # Configure requests allowed from specific origins.
    allowedOrigins: ['*']
